### ISSUE TITLE
Doesn't work with extra indexes

### ISSUE THREAD

**Issue by shchemelevev** [MeanderingProgrammer/py-requirements.nvim#12]
I have the following configuration. The modules published to artifactory are not found by the plugin.
```
$ cat ~/.pip/pip.conf 
[global]
index-url = https://pypi.org/simple/
extra-index-url=https://artifactory.customdomain.org/artifactory/api/pypi/pypi-virtual/simple
```

**Comment by MeanderingProgrammer** [comment]
Hi there,

Good callout, have added this as a known limitation, currently pip.conf is not read in any way.

If someone wants to provide a PR for this more than happy to look it over.

**Comment by shchemelevev** [comment]
Looks like the easiest way to add this feature is to add `index-url` and `extra-index-url` as configuration options. This will eliminate the need to find and parse `pip.conf`. I'll try to do that when I'll have time.

**Comment by MeanderingProgrammer** [comment]
Implemented here: https://github.com/MeanderingProgrammer/py-requirements.nvim/commit/b178a0b444ddf3307a68c8c9ac0a639bd8e19ed5
