### ISSUE TITLE
Error Vim(append):Error executing lua callback: ...ata/lazy/py-requirements.nvim/lua/py-requirements/ui.lua:63: attempt to call field 'iter' (a nil value) stack traceback

### ISSUE THREAD

**Issue by Barmaley0** [MeanderingProgrammer/py-requirements.nvim#13]
What could be the problem?
![image](https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/133758633/83762567-3d99-46db-85a5-28b073a19e0b)

Windows 10
Neovim 0.9.5

![image](https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/133758633/83e30fcd-b7db-4a06-b23e-0a838a97f315)
![image](https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/133758633/3199e112-d07d-4841-9075-ec74c4a55114)

**Comment by MeanderingProgrammer** [comment]
Ah, this plugin requires neovim version `0.10.0`. Mainly to take advantage of new options in diagnostics. Done here: https://github.com/MeanderingProgrammer/py-requirements.nvim/commit/868465a06bd2aaa3b08c85768924391f3179c25d.

I had added this to the healthcheck but did not update the README with this information, will add that now.

Versions at this commit or before, https://github.com/MeanderingProgrammer/py-requirements.nvim/commit/76baf1f056f7b8bfa8f17e5daae54a6f1c887b88, will work with 0.9.5, but require plenary as a dependency.

**Comment by MeanderingProgrammer** [comment]
Updated the README. Sorry for any inconvenience!

**Comment by Barmaley0** [comment]
I've rolled back to this commit 76baf1f, but I'm still having problems with syntax highlighting. What could be the problem?
![image](https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/133758633/1f00cec0-69b0-487b-a2b5-2504c1bac8f3)

**Comment by MeanderingProgrammer** [comment]
Are you referring to the version number being highlighted in the demo?

This is up to treesitter / your color scheme. This plugin including older versions doesn't touch any of that.

If you put the cursor over one of the version values like in your screenshot and then run the `:Inspect` command Neovim will tell you what highlight group is being used. In my case I get:

![highlight](https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/52591095/40b565bf-f76c-4768-ac67-93af50bb9677)

The color scheme I use [rose-pine](https://github.com/rose-pine/neovim) just happens to set `Number` to that yellow color.

**Comment by Barmaley0** [comment]
I understand. I have treуsitеer running everywhere. In addition to the requirements, although I did all the installations and registered the settings.
![image](https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/133758633/18175f0d-e67f-4e5f-a1c5-33c549df23b3)

**Comment by MeanderingProgrammer** [comment]
I meant in your most recent screenshot, where you had the requirements file open.

So if you open a file with python requirements and put your cursor over a version like so:

![hover-version](https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/52591095/ffbf4829-36e9-47ac-b772-db48f68e9864)

- In this case my cursor is in the `8.1.7` section

Then run the `:Inspect` command:

![run-inspect](https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/52591095/2ff686f4-f436-499e-935f-13efdcc7e5ca)

You should get an output that looks something like this:

![result](https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/52591095/cb2f8a65-a025-4c86-add6-fa7caf6c6ab0)

Which will tell you why the versions are highlighted the way they are.

**Comment by Barmaley0** [comment]
I understand you. Wanted to say. The color syntax does not work in the requirements file.
![image](https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/133758633/c941d700-c5b8-43dd-84e5-819694238551)
Everything is fine in other files
![image](https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/133758633/bab351a4-d1aa-469e-9eeb-aa349b5386d5)

**Comment by MeanderingProgrammer** [comment]
I did some more looking into this and figured out what's going on.

Support for the `requirements` filetype for `requirements.txt` was added here: https://github.com/neovim/neovim/pull/24638.

So you would need a version of Neovim after this PR, which would be `0.10.0` and above I believe.

Or you can add the following somewhere in your config:

```lua
vim.filetype.add({
    filename = {
        ['requirements.txt'] = 'requirements',
    },
})
```

**Comment by Barmaley0** [comment]
Everything is working. Thank you.
![image](https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/133758633/3ffa7a67-1547-4f65-b62d-48df4ecf4642)
Config
![image](https://github.com/MeanderingProgrammer/py-requirements.nvim/assets/133758633/bb4d172f-01f8-47d0-908a-7387fe61f212)
