### ISSUE TITLE
Using `InsertLeave` or `InsertLeavePre` instead of `TextChangedI`?

### ISSUE THREAD

**Issue by SWiegandt** [MeanderingProgrammer/py-requirements.nvim#6]
There's a noticeable lag on my laptop when typing in a requirements file due to the diagnostics rendering running on `TextChangedI`. I'm wondering if it's necessary, or even desirable, to update the display on each keystroke, or if it could be changed to only update on leaving insert mode?

edit: Or it could also be configurable with some sensible defaults if you want to keep it more general, I suppose.

**Comment by MeanderingProgrammer** [comment]
Huh, that's a good point, I copied that setup from crates.nvim, didn't really think much of it.

However I'm not really getting any lag on my side, does this happen with larger files, or generally in what scenarios do you notice this?

**Comment by SWiegandt** [comment]
It happens on files of pretty much any size. Thinking about the mechanics of it, I think it's probably mostly due to the calls to pypi on each stroke that corresponds to a package that isn't cached, meaning that typing a version number doesn't lag, but manually typing in a new package name does.

**Comment by MeanderingProgrammer** [comment]
Agree with the problem and the suggested solution, merged: https://github.com/MeanderingProgrammer/py-requirements.nvim/commit/bf5aff810d408fa69b57c35ff807594f3132f046
